# fly.toml app configuration file generated for keirin-odds on 2025-05-25T23:36:46+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'keirin-odds'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8076
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
